# Generated by Django 2.2 on 2019-04-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='slug',
        ),
    ]
