# Generated by Django 2.2 on 2019-04-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framework', '__first__'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='framework.Framework'),
        ),
    ]
