# Generated by Django 2.2 on 2019-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
