# Generated by Django 2.2 on 2019-04-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connect',
            old_name='icon',
            new_name='icon_url',
        ),
    ]
