# Generated by Django 2.2 on 2019-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20190412_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='url',
            field=models.CharField(default='https://www.google.com', max_length=200),
            preserve_default=False,
        ),
    ]
